# Base configuration for MT-Bench tasks
preprocessor: MultiturnPreprocessor
postprocessor: MultiturnPostprocessor
dataset_path: ServiceNow-AI/mt-bench_audio
language: en
split: test
audio_column: audio
target_column: reference
textual_input_column: turns
id_column: question_id
long_audio_processing_logic: truncate

generation_kwargs:
  temperature: 0.0
  do_sample: false
  max_gen_tokens: 64

metrics:
  - metric: mt_bench_llm_judge