task_name: asvspoof
dataset_path: DynamicSuperb/SpoofDetection_ASVspoof2017
modality: audio
language: en
split: test
preprocessor: GeneralPreprocessor
postprocessor: GeneralPostprocessor
audio_column: audio
target_column: label
instruction_column: instruction
user_prompt: "Please listen to the following audio clip and analyze the speaker's voice characteristics, such as pitch, tone, timbre, and speech patterns. Choose from the following options: authentic, spoofed. Be brief. Do not provide explanations."
long_audio_processing_logic: truncate

generation_kwargs:
  temperature: 0.0001
  do_sample: false
  max_gen_tokens: 64

metrics:
  - metric: llm_judge_binary
  - metric: detailed_judge_prompt