#!/bin/bash

# Create YAML files for all FLEURS languages
create_fleurs_yaml() {
    local name=$1
    local subset=$2
    local lang=$3
    
    cat > "fleurs_${subset}.yaml" << EOL
task_name: fleurs_${subset}
extends: ["./base.yaml#"]
subset: ${subset}
language: ${lang}
EOL
    echo "Created fleurs_${subset}.yaml"
}

# Creating all FLEURS language YAML files
create_fleurs_yaml "fleurs_af" "af_za" "af"
create_fleurs_yaml "fleurs_am" "am_et" "am"
create_fleurs_yaml "fleurs_ar" "ar_eg" "ar"
create_fleurs_yaml "fleurs_hy" "hy_am" "hy"
create_fleurs_yaml "fleurs_as" "as_in" "as"
create_fleurs_yaml "fleurs_ast" "ast_es" "ast"
create_fleurs_yaml "fleurs_az" "az_az" "az"
create_fleurs_yaml "fleurs_be" "be_by" "be"
create_fleurs_yaml "fleurs_bn" "bn_in" "bn"
create_fleurs_yaml "fleurs_bs" "bs_ba" "bs"
create_fleurs_yaml "fleurs_bg" "bg_bg" "bg"
create_fleurs_yaml "fleurs_my" "my_mm" "my"
create_fleurs_yaml "fleurs_ca" "ca_es" "ca"
create_fleurs_yaml "fleurs_ceb" "ceb_ph" "ceb"
create_fleurs_yaml "fleurs_cmn_hans" "cmn_hans_cn" "cmn"
create_fleurs_yaml "fleurs_yue_hant" "yue_hant_hk" "yue"
create_fleurs_yaml "fleurs_hr" "hr_hr" "hr"
create_fleurs_yaml "fleurs_cs" "cs_cz" "cs"
create_fleurs_yaml "fleurs_da" "da_dk" "da"
create_fleurs_yaml "fleurs_nl" "nl_nl" "nl"
create_fleurs_yaml "fleurs_en" "en_us" "en"
create_fleurs_yaml "fleurs_et" "et_ee" "et"
create_fleurs_yaml "fleurs_fil" "fil_ph" "fil"
create_fleurs_yaml "fleurs_fi" "fi_fi" "fi"
create_fleurs_yaml "fleurs_fr" "fr_fr" "fr"
create_fleurs_yaml "fleurs_ff" "ff_sn" "ff"
create_fleurs_yaml "fleurs_gl" "gl_es" "gl"
create_fleurs_yaml "fleurs_lg" "lg_ug" "lg"
create_fleurs_yaml "fleurs_ka" "ka_ge" "ka"
create_fleurs_yaml "fleurs_de" "de_de" "de"
create_fleurs_yaml "fleurs_el" "el_gr" "el"
create_fleurs_yaml "fleurs_gu" "gu_in" "gu"
create_fleurs_yaml "fleurs_ha" "ha_ng" "ha"
create_fleurs_yaml "fleurs_he" "he_il" "he"
create_fleurs_yaml "fleurs_hi" "hi_in" "hi"
create_fleurs_yaml "fleurs_hu" "hu_hu" "hu"
create_fleurs_yaml "fleurs_is" "is_is" "is"
create_fleurs_yaml "fleurs_ig" "ig_ng" "ig"
create_fleurs_yaml "fleurs_id" "id_id" "id"
create_fleurs_yaml "fleurs_ga" "ga_ie" "ga"
create_fleurs_yaml "fleurs_it" "it_it" "it"
create_fleurs_yaml "fleurs_ja" "ja_jp" "ja"
create_fleurs_yaml "fleurs_jv" "jv_id" "jv"
create_fleurs_yaml "fleurs_kea" "kea_cv" "kea"
create_fleurs_yaml "fleurs_kam" "kam_ke" "kam"
create_fleurs_yaml "fleurs_kn" "kn_in" "kn"
create_fleurs_yaml "fleurs_kk" "kk_kz" "kk"
create_fleurs_yaml "fleurs_km" "km_kh" "km"
create_fleurs_yaml "fleurs_ko" "ko_kr" "ko"
create_fleurs_yaml "fleurs_ky" "ky_kg" "ky"
create_fleurs_yaml "fleurs_lo" "lo_la" "lo"
create_fleurs_yaml "fleurs_lv" "lv_lv" "lv"
create_fleurs_yaml "fleurs_ln" "ln_cd" "ln"
create_fleurs_yaml "fleurs_lt" "lt_lt" "lt"
create_fleurs_yaml "fleurs_luo" "luo_ke" "luo"
create_fleurs_yaml "fleurs_lb" "lb_lu" "lb"
create_fleurs_yaml "fleurs_mk" "mk_mk" "mk"
create_fleurs_yaml "fleurs_ms" "ms_my" "ms"
create_fleurs_yaml "fleurs_ml" "ml_in" "ml"
create_fleurs_yaml "fleurs_mt" "mt_mt" "mt"
create_fleurs_yaml "fleurs_mi" "mi_nz" "mi"
create_fleurs_yaml "fleurs_mr" "mr_in" "mr"
create_fleurs_yaml "fleurs_mn" "mn_mn" "mn"
create_fleurs_yaml "fleurs_ne" "ne_np" "ne"
create_fleurs_yaml "fleurs_nso" "nso_za" "nso"
create_fleurs_yaml "fleurs_nb" "nb_no" "nb"
create_fleurs_yaml "fleurs_ny" "ny_mw" "ny"
create_fleurs_yaml "fleurs_oc" "oc_fr" "oc"
create_fleurs_yaml "fleurs_or" "or_in" "or"
create_fleurs_yaml "fleurs_om" "om_et" "om"
create_fleurs_yaml "fleurs_ps" "ps_af" "ps"
create_fleurs_yaml "fleurs_fa" "fa_ir" "fa"
create_fleurs_yaml "fleurs_pl" "pl_pl" "pl"
create_fleurs_yaml "fleurs_pt" "pt_br" "pt"
create_fleurs_yaml "fleurs_pa" "pa_in" "pa"
create_fleurs_yaml "fleurs_ro" "ro_ro" "ro"
create_fleurs_yaml "fleurs_ru" "ru_ru" "ru"
create_fleurs_yaml "fleurs_sr" "sr_rs" "sr"
create_fleurs_yaml "fleurs_sn" "sn_zw" "sn"
create_fleurs_yaml "fleurs_sd" "sd_in" "sd"
create_fleurs_yaml "fleurs_sk" "sk_sk" "sk"
create_fleurs_yaml "fleurs_sl" "sl_si" "sl"
create_fleurs_yaml "fleurs_so" "so_so" "so"
create_fleurs_yaml "fleurs_ckb" "ckb_iq" "ckb"
create_fleurs_yaml "fleurs_es" "es_419" "es"
create_fleurs_yaml "fleurs_sw" "sw_ke" "sw"
create_fleurs_yaml "fleurs_sv" "sv_se" "sv"
create_fleurs_yaml "fleurs_tg" "tg_tj" "tg"
create_fleurs_yaml "fleurs_ta" "ta_in" "ta"
create_fleurs_yaml "fleurs_te" "te_in" "te"
create_fleurs_yaml "fleurs_th" "th_th" "th"
create_fleurs_yaml "fleurs_tr" "tr_tr" "tr"
create_fleurs_yaml "fleurs_uk" "uk_ua" "uk"
create_fleurs_yaml "fleurs_umb" "umb_ao" "umb"
create_fleurs_yaml "fleurs_ur" "ur_pk" "ur"
create_fleurs_yaml "fleurs_uz" "uz_uz" "uz"
create_fleurs_yaml "fleurs_vi" "vi_vn" "vi"
create_fleurs_yaml "fleurs_cy" "cy_gb" "cy"
create_fleurs_yaml "fleurs_wo" "wo_sn" "wo"
create_fleurs_yaml "fleurs_xh" "xh_za" "xh"
create_fleurs_yaml "fleurs_yo" "yo_ng" "yo"
create_fleurs_yaml "fleurs_zu" "zu_za" "zu"

echo "All FLEURS language YAML files created successfully!"