
dataset_metric:
  - "(audiobench_wavcaps_qa_test, word_error_rate)"
  - "(audiobench_alpaca_audio_test, word_error_rate)"
batch_size: 4
num_samples: 100
judge_concurrency: 8
judge_model: "gpt-4o-mini"

models:
  - name: "audio_transcriptions_openai"
    info:
      inference_type: "inference_server"
      url: "${ENDPOINT_URL}"
      delay: 100
      retry_attempts: 8
      timeout: 30
      sync_client: false
      postprocessor: []
      model: "whisper-3"
      auth_token: "${AUTH_TOKEN}"