
dataset_metric: #tuple of dataset, metric
  - "(wavcaps_qa_test, word_error_rate)"
  - "(alpaca_audio_test, word_error_rate)"
num_samples: 100 #number of samples to run(remove for all)
judge_concurrency: 8 #judge call(optional)
judge_model: "gpt-4o-mini" #optional(only supported model right no2)

models:
  - info:
      name: "audio_transcriptions_openai" 
      inference_type: "vllm" #you can use vllm, openai, (chat completion) or audio transcription endpoint
      url: "${ENDPOINT_URL}" - #endpoint url
      delay: 100
      retry_attempts: 8
      timeout: 30
      model: "whisper-3" #only needed for vllm
      auth_token: "${AUTH_TOKEN}" 
      batch_size: 4 #batch eval size
      chunk_size: 45 #max audio length in seconds fed to model