dataset_metric:
  - "(earnings21_test, word_error_rate)"
judge_concurrency: 4
judge_model: "gpt-4o-mini"
num_samples: 1
models:
  - info:
      name: "audio_transcriptions_openai_1"
      inference_type: "inference_server"
      url: "https://844b3c14-08c9-4de3-8c0b-79c84ef528ca-8000.job.console.elementai.com/v1/audio/transcriptions"
      delay: 100
      retry_attempts: 8
      timeout: 30
      postprocessor: []
      model: "whisper-3"
      auth_token: "Bearer 8o30OElfDYV_D6YbbznT0A:GDC2BsXIfSdfjv9iWka3V4MkazpvHfe0cCwXohzbP0Q"
      batch_size: 50
      chunk_size: 30