dataset_metric:
  - "(audiobench_wavcaps_qa_test, llm_judge_binary)"
  - "(audiobench_alpaca_audio_test, llm_judge_detailed)"
judge_concurrency: 4
num_samples: 10
judge_model: "gpt-4o-mini"

models:
  - info:
      name: "gpt4o-run1"
      inference_type: "openai"
      url: "https://corelmm-gpt-4t.openai.azure.com/openai/deployments/gpt-4o-mini-audio-preview/chat/completions?api-version=2025-01-01-preview"
      delay: 100
      retry_attempts: 8
      timeout: 30
      postprocessor: []
      model: "gpt-4o-mini-audio-preview"
      auth_token: "e6458032207a4920b3b0d2d797242eda"
      batch_size: 3
  - info:
      name: "gpt4o-run2"
      inference_type: "openai"
      url: "https://corelmm-gpt-4t.openai.azure.com/openai/deployments/gpt-4o-mini-audio-preview/chat/completions?api-version=2025-01-01-preview"
      delay: 100
      retry_attempts: 8
      timeout: 30
      postprocessor: []
      model: "gpt-4o-mini-audio-preview"
      auth_token: "e6458032207a4920b3b0d2d797242eda"
      batch_size: 2