# Base configuration for all BFCL tasks
dataset_path: ServiceNow-AI/BFCL_v3_audio
language: en
preprocessor: BfclPreprocessor
postprocessor: BfclPostprocessor
long_audio_processing_logic: truncate

generation_kwargs:
  temperature: 0.0
  do_sample: false
  max_gen_tokens: 64

metrics:
  - metric: bfcl_match_score
